# 设置版本号、头文件名、代码库名称等。
set(PUGIXML_NAME pugixml-release-static)
set(PUGIXML_HEADER_NAME pugixml.hpp)
set(PUGIXML_LIBRARY_NAME pugixml.lib)
set(PUGIXML_DIRECTORY ${DEPENDENCIES_DIRECTORY}/pugixml)
set(PUGIXML_INSTALL_DIRECTORY ${PUGIXML_DIRECTORY}/install)
set(PUGIXML_HEADERS_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/include)
set(PUGIXML_BINARY_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/bin)
set(PUGIXML_LIBRARY_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        PUGIXML_INCLUDE_DIRECTORY
        NAMES ${PUGIXML_HEADER_NAME}
        PATHS ${PUGIXML_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (PUGIXML_INCLUDE_DIRECTORY)
    message(STATUS "found pugixml include directory ${PUGIXML_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_library(
        PUGIXML_LIBRARY
        NAMES ${PUGIXML_LIBRARY_NAME}
        PATHS ${PUGIXML_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (PUGIXML_LIBRARY)
    message(STATUS "found pugixml library ${PUGIXML_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT (PUGIXML_INCLUDE_DIRECTORY AND PUGIXML_LIBRARY))
    include(ExternalProject)
    set(PUGIXML_COMPILE_FLAGS "${LIBRARY_COMPILE_CXX_FLAGS} /DPUGIXML_HAS_LONG_LONG /DPUGIXML_HAS_STRING_VIEW")
    set(PUGIXML_BUILD_DIRECTORY ${PUGIXML_DIRECTORY}/build)
    set(PUGIXML_SOURCE_DIRECTORY ${PUGIXML_DIRECTORY}/source)
    ExternalProject_Add(
            ${PUGIXML_NAME}
            PREFIX ${PUGIXML_DIRECTORY}
            URL ${PUGIXML_URL}
            URL_HASH SHA256=${PUGIXML_SHA256}
            SOURCE_DIR ${PUGIXML_SOURCE_DIRECTORY}
            BINARY_DIR ${PUGIXML_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${PUGIXML_SOURCE_DIRECTORY} -B ${PUGIXML_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${PUGIXML_INSTALL_DIRECTORY}
                -DCMAKE_CONFIGURATION_TYPES=${CMAKE_BUILD_TYPE}
                -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
                -DCMAKE_CXX_FLAGS=${PUGIXML_COMPILE_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(PUGIXML_INCLUDE_DIRECTORY ${PUGIXML_HEADERS_DIRECTORY})
    set(PUGIXML_LIBRARY ${PUGIXML_LIBRARY_DIRECTORY}/${PUGIXML_LIBRARY_NAME})
    list(APPEND DEPENDENCIES ${PUGIXML_NAME})
    unset(PUGIXML_COMPILE_FLAGS)
    unset(PUGIXML_BUILD_DIRECTORY)
    unset(PUGIXML_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${PUGIXML_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${PUGIXML_LIBRARY})

unset(PUGIXML_HEADER_NAME)
unset(PUGIXML_LIBRARY_NAME)
unset(PUGIXML_DYNAMIC_LIBRARY_NAME)
unset(PUGIXML_DIRECTORY)
unset(PUGIXML_INSTALL_DIRECTORY)
unset(PUGIXML_HEADERS_DIRECTORY)
unset(PUGIXML_BINARY_DIRECTORY)
unset(PUGIXML_LIBRARY_DIRECTORY)
