# 设置版本号、头文件名、代码库名称等。
set(ARGPARSE_NAME argparse-debug-static)
set(ARGPARSE_HEADER_NAME argparse/argparse.hpp)
set(ARGPARSE_DIRECTORY ${DEPENDENCIES_DIRECTORY}/argparse)
set(ARGPARSE_INSTALL_DIRECTORY ${ARGPARSE_DIRECTORY}/install)
set(ARGPARSE_HEADERS_DIRECTORY ${ARGPARSE_INSTALL_DIRECTORY}/include)

# 查找头文件所在文件夹。
find_path(
        ARGPARSE_INCLUDE_DIRECTORY
        NAMES ${ARGPARSE_HEADER_NAME}
        PATHS ${ARGPARSE_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (ARGPARSE_INCLUDE_DIRECTORY)
    message(STATUS "found argparse include directory ${ARGPARSE_INCLUDE_DIRECTORY}")
endif ()

# 添加外部构建项目。
if (NOT ARGPARSE_INCLUDE_DIRECTORY)
    include(ExternalProject)
    set(ARGPARSE_BUILD_DIRECTORY ${ARGPARSE_DIRECTORY}/build)
    set(ARGPARSE_SOURCE_DIRECTORY ${ARGPARSE_DIRECTORY}/source)
    ExternalProject_Add(
            ${ARGPARSE_NAME}
            PREFIX ${ARGPARSE_DIRECTORY}
            URL ${ARGPARSE_URL}
            URL_HASH SHA256=${ARGPARSE_SHA256}
            SOURCE_DIR ${ARGPARSE_SOURCE_DIRECTORY}
            BINARY_DIR ${ARGPARSE_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${ARGPARSE_SOURCE_DIRECTORY} -B ${ARGPARSE_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${ARGPARSE_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_CXX_FLAGS=${LIBRARY_COMPILE_CXX_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DARGPARSE_BUILD_TESTS=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${ARGPARSE_BUILD_DIRECTORY} --parallel --config ${CMAKE_BUILD_TYPE} --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${ARGPARSE_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(ARGPARSE_INCLUDE_DIRECTORY ${ARGPARSE_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${ARGPARSE_NAME})
    unset(ARGPARSE_BUILD_DIRECTORY)
    unset(ARGPARSE_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${ARGPARSE_INCLUDE_DIRECTORY})

unset(ARGPARSE_HEADER_NAME)
unset(ARGPARSE_DIRECTORY)
unset(ARGPARSE_INSTALL_DIRECTORY)
unset(ARGPARSE_HEADERS_DIRECTORY)
