# 设置版本号、头文件名、代码库名称等。
set(BZIP2_NAME bzip2-release-dynamic)
set(BZIP2_HEADER_NAME bzlib.h)
set(BZIP2_DYNAMIC_LIBRARY_NAME libbz2.so.1.0.9)
set(BZIP2_DIRECTORY ${DEPENDENCIES_DIRECTORY}/bzip2)
set(BZIP2_INSTALL_DIRECTORY ${BZIP2_DIRECTORY}/install)
set(BZIP2_HEADERS_DIRECTORY ${BZIP2_INSTALL_DIRECTORY}/include)
set(BZIP2_LIBRARY_DIRECTORY ${BZIP2_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        BZIP2_INCLUDE_DIRECTORY
        NAMES ${BZIP2_HEADER_NAME}
        PATHS ${BZIP2_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (BZIP2_INCLUDE_DIRECTORY)
    message(STATUS "found bzip2 include directory ${BZIP2_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_file(
        BZIP2_DYNAMIC_LIBRARY
        NAMES ${BZIP2_DYNAMIC_LIBRARY_NAME}
        PATHS ${BZIP2_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (BZIP2_DYNAMIC_LIBRARY)
    message(STATUS "found bzip2 dynamic library ${BZIP2_DYNAMIC_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT (BZIP2_DYNAMIC_LIBRARY AND BZIP2_INCLUDE_DIRECTORY))
    include(ExternalProject)
    set(BZIP2_BUILD_DIRECTORY ${BZIP2_DIRECTORY}/build)
    set(BZIP2_SOURCE_DIRECTORY ${BZIP2_DIRECTORY}/source)
    ExternalProject_Add(
            ${BZIP2_NAME}
            PREFIX ${BZIP2_DIRECTORY}
            URL ${BZIP2_URL}
            URL_HASH SHA256=${BZIP2_SHA256}
            SOURCE_DIR ${BZIP2_SOURCE_DIRECTORY}
            BINARY_DIR ${BZIP2_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${BZIP2_SOURCE_DIRECTORY} -B ${BZIP2_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${BZIP2_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_C_FLAGS=${LIBRARY_COMPILE_C_FLAGS}
                -DCMAKE_C_FLAGS_DEBUG=${LIBRARY_COMPILE_C_FLAGS_DEBUG}
                -DCMAKE_C_FLAGS_RELEASE=${LIBRARY_COMPILE_C_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=ON
                -DENABLE_EXAMPLES=OFF
                -DENABLE_SHARED_LIB:BOOL=ON
                -DENABLE_DOCS=OFF
                -DENABLE_STATIC_LIB:BOOL=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${BZIP2_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${BZIP2_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(BZIP2_INCLUDE_DIRECTORY ${BZIP2_HEADERS_DIRECTORY})
    set(BZIP2_DYNAMIC_LIBRARY ${BZIP2_LIBRARY_DIRECTORY}/${BZIP2_DYNAMIC_LIBRARY_NAME})
    list(APPEND DEPENDENCIES ${BZIP2_NAME})
    unset(BZIP2_BUILD_DIRECTORY)
    unset(BZIP2_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${BZIP2_INCLUDE_DIRECTORY})
list(APPEND DYNAMIC_LIBRARIES ${BZIP2_DYNAMIC_LIBRARY})

unset(BZIP2_HEADER_NAME)
unset(BZIP2_DYNAMIC_LIBRARY_NAME)
unset(BZIP2_DIRECTORY)
unset(BZIP2_INSTALL_DIRECTORY)
unset(BZIP2_HEADERS_DIRECTORY)
unset(BZIP2_LIBRARY_DIRECTORY)
