# 设置版本号、头文件名、代码库名称等。
set(YAML_CPP_NAME yaml-cpp-release-static)
set(YAML_CPP_HEADER_NAME yaml-cpp/yaml.h)
set(YAML_CPP_LIBRARY_NAME libyaml-cpp.a)
set(YAML_CPP_DIRECTORY ${DEPENDENCIES_DIRECTORY}/yaml-cpp)
set(YAML_CPP_INSTALL_DIRECTORY ${YAML_CPP_DIRECTORY}/install)
set(YAML_CPP_LIBRARY_DIRECTORY ${YAML_CPP_INSTALL_DIRECTORY}/lib)
set(YAML_CPP_HEADERS_DIRECTORY ${YAML_CPP_INSTALL_DIRECTORY}/include)

# 查找头文件所在文件夹。
find_path(
        YAML_CPP_INCLUDE_DIRECTORY
        NAMES ${YAML_CPP_HEADER_NAME}
        PATHS ${YAML_CPP_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (YAML_CPP_INCLUDE_DIRECTORY)
    message(STATUS "found yaml-cpp include directory ${YAML_CPP_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_library(
        YAML_CPP_LIBRARY
        NAMES ${YAML_CPP_LIBRARY_NAME}
        PATHS ${YAML_CPP_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (YAML_CPP_LIBRARY)
    message(STATUS "found yaml-cpp library ${YAML_CPP_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT (YAML_CPP_LIBRARY AND YAML_CPP_INCLUDE_DIRECTORY))
    include(ExternalProject)
    set(YAML_CPP_BUILD_DIRECTORY ${YAML_CPP_DIRECTORY}/build)
    set(YAML_CPP_SOURCE_DIRECTORY ${YAML_CPP_DIRECTORY}/source)
    ExternalProject_Add(
            ${YAML_CPP_NAME}
            PREFIX ${YAML_CPP_DIRECTORY}
            URL ${YAML_CPP_URL}
            URL_HASH SHA256=${YAML_CPP_SHA256}
            SOURCE_DIR ${YAML_CPP_SOURCE_DIRECTORY}
            BINARY_DIR ${YAML_CPP_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${YAML_CPP_SOURCE_DIRECTORY} -B ${YAML_CPP_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${YAML_CPP_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_CXX_FLAGS=${LIBRARY_COMPILE_CXX_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DYAML_BUILD_SHARED_LIBS:BOOL=OFF
                -DYAML_CPP_BUILD_TESTS=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${YAML_CPP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${YAML_CPP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(YAML_CPP_LIBRARY ${YAML_CPP_LIBRARY_DIRECTORY}/${YAML_CPP_LIBRARY_NAME})
    set(YAML_CPP_INCLUDE_DIRECTORY ${YAML_CPP_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${YAML_CPP_NAME})
    unset(YAML_CPP_BUILD_DIRECTORY)
    unset(YAML_CPP_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND DEFINITIONS "-DYAML_CPP_STATIC_DEFINE=1")
list(APPEND INCLUDES ${YAML_CPP_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${YAML_CPP_LIBRARY})

unset(YAML_CPP_HEADER_NAME)
unset(YAML_CPP_LIBRARY_NAME)
unset(YAML_CPP_DIRECTORY)
unset(YAML_CPP_INSTALL_DIRECTORY)
unset(YAML_CPP_LIBRARY_DIRECTORY)
unset(YAML_CPP_HEADERS_DIRECTORY)
