# 设置版本号、头文件名、代码库名称等。
set(ZLIB_NAME zlib-debug-static)
set(ZLIB_HEADER_NAME zlib.h)
set(ZLIB_LIBRARY_NAME libz.a)
set(ZLIB_DIRECTORY ${DEPENDENCIES_DIRECTORY}/zlib)
set(ZLIB_INSTALL_DIRECTORY ${ZLIB_DIRECTORY}/install)
set(ZLIB_HEADERS_DIRECTORY ${ZLIB_INSTALL_DIRECTORY}/include)
set(ZLIB_LIBRARY_DIRECTORY ${ZLIB_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        ZLIB_INCLUDE_DIRECTORY
        NAMES ${ZLIB_HEADER_NAME}
        PATHS ${ZLIB_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (ZLIB_INCLUDE_DIRECTORY)
    message(STATUS "found zlib include directory ${ZLIB_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_library(
        ZLIB_LIBRARY
        NAMES ${ZLIB_LIBRARY_NAME}
        PATHS ${ZLIB_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (ZLIB_LIBRARY)
    message(STATUS "found zlib library ${ZLIB_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT (ZLIB_INCLUDE_DIRECTORY AND ZLIB_LIBRARY))
    include(ExternalProject)
    set(ZLIB_BUILD_DIRECTORY ${ZLIB_DIRECTORY}/build)
    set(ZLIB_SOURCE_DIRECTORY ${ZLIB_DIRECTORY}/source)
    ExternalProject_Add(
            ${ZLIB_NAME}
            PREFIX ${ZLIB_DIRECTORY}
            URL ${ZLIB_URL}
            URL_HASH SHA256=${ZLIB_SHA256}
            SOURCE_DIR ${ZLIB_SOURCE_DIRECTORY}
            BINARY_DIR ${ZLIB_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${ZLIB_SOURCE_DIRECTORY} -B ${ZLIB_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${ZLIB_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_C_FLAGS=${LIBRARY_COMPILE_C_FLAGS}
                -DCMAKE_C_FLAGS_DEBUG=${LIBRARY_COMPILE_C_FLAGS_DEBUG}
                -DCMAKE_C_FLAGS_RELEASE=${LIBRARY_COMPILE_C_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DZLIB_BUILD_TESTING=OFF
                -DZLIB_BUILD_SHARED:BOOL=OFF
                -DZLIB_BUILD_MINIZIP=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${ZLIB_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${ZLIB_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(ZLIB_INCLUDE_DIRECTORY ${ZLIB_HEADERS_DIRECTORY})
    set(ZLIB_LIBRARY ${ZLIB_LIBRARY_DIRECTORY}/${ZLIB_LIBRARY_NAME})
    list(APPEND DEPENDENCIES ${ZLIB_NAME})
    unset(ZLIB_BUILD_DIRECTORY)
    unset(ZLIB_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${ZLIB_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${ZLIB_LIBRARY})

unset(ZLIB_HEADER_NAME)
unset(ZLIB_LIBRARY_NAME)
unset(ZLIB_DIRECTORY)
unset(ZLIB_INSTALL_DIRECTORY)
unset(ZLIB_HEADERS_DIRECTORY)
unset(ZLIB_LIBRARY_DIRECTORY)
