# 设置版本号、头文件名、代码库名称等。
set(LIBZIP_VERSION v1.11.4)
set(LIBZIP_HEADER_NAME zip.h)
set(LIBZIP_LIBRARY_NAME zip.lib)
set(LIBZIP_DYNAMIC_LIBRARY_NAME zip.dll)
set(LIBZIP_DIRECTORY ${DEPENDENCIES_DIRECTORY}/libzip)
set(LIBZIP_INSTALL_DIRECTORY ${LIBZIP_DIRECTORY}/install)
set(LIBZIP_LIBRARY_DIRECTORY ${LIBZIP_INSTALL_DIRECTORY}/lib)
set(LIBZIP_HEADERS_DIRECTORY ${LIBZIP_INSTALL_DIRECTORY}/include)
set(LIBZIP_BINARY_DIRECTORY ${LIBZIP_INSTALL_DIRECTORY}/bin)

# 查找头文件所在文件夹。
find_path(
        LIBZIP_INCLUDE_DIRECTORY
        NAMES ${LIBZIP_HEADER_NAME}
        PATHS ${LIBZIP_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (LIBZIP_INCLUDE_DIRECTORY)
    message(STATUS "found libzip include directory ${LIBZIP_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_file(
        LIBZIP_DYNAMIC_LIBRARY
        NAMES ${LIBZIP_DYNAMIC_LIBRARY_NAME}
        PATHS ${LIBZIP_BINARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (LIBZIP_DYNAMIC_LIBRARY)
    message(STATUS "found libzip dynamic library ${LIBZIP_DYNAMIC_LIBRARY}")
endif ()
find_library(
        LIBZIP_LIBRARY
        NAMES ${LIBZIP_LIBRARY_NAME}
        PATHS ${LIBZIP_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (LIBZIP_LIBRARY)
    message(STATUS "found libzip library ${LIBZIP_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT ((COMPILE_STATIC_MODE AND LIBZIP_LIBRARY AND LIBZIP_INCLUDE_DIRECTORY) OR (COMPILE_DYNAMIC_MODE AND LIBZIP_DYNAMIC_LIBRARY AND LIBZIP_LIBRARY AND LIBZIP_INCLUDE_DIRECTORY)))
    include(ExternalProject)
    set(LIBZIP_BUILD_DIRECTORY ${LIBZIP_DIRECTORY}/build)
    set(LIBZIP_SOURCE_DIRECTORY ${LIBZIP_DIRECTORY}/source)
    set(LIBZIP_COMPILE_FLAGS "${LIBRARY_COMPILE_C_FLAGS}")
    set(LIBZIP_COMPILE_FLAGS_DEBUG "${LIBRARY_COMPILE_C_FLAGS_DEBUG} /DLZMA_API_STATIC")
    set(LIBZIP_COMPILE_FLAGS_RELEASE "${LIBRARY_COMPILE_C_FLAGS_RELEASE} /DLZMA_API_STATIC")
    set(LIBZIP_NAME libzip-static)
    if (COMPILE_DYNAMIC_MODE)
        set(LIBZIP_NAME libzip-dynamic)
        set(LIBZIP_COMPILE_FLAGS_DEBUG "${LIBRARY_COMPILE_C_FLAGS_DEBUG}")
        set(LIBZIP_COMPILE_FLAGS_RELEASE "${LIBRARY_COMPILE_C_FLAGS_RELEASE}")
    endif ()
    ExternalProject_Add(
            ${LIBZIP_NAME}
            PREFIX ${LIBZIP_DIRECTORY}
            URL https://github.com/nih-at/libzip/archive/refs/tags/${LIBZIP_VERSION}.zip
            SOURCE_DIR ${LIBZIP_SOURCE_DIRECTORY}
            BINARY_DIR ${LIBZIP_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${LIBZIP_SOURCE_DIRECTORY} -B ${LIBZIP_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${LIBZIP_INSTALL_DIRECTORY}
                -DCMAKE_CONFIGURATION_TYPES=${CMAKE_BUILD_TYPE}
                -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
                -DCMAKE_C_FLAGS=${LIBZIP_COMPILE_FLAGS}
                -DCMAKE_C_FLAGS_DEBUG=${LIBZIP_COMPILE_FLAGS_DEBUG}
                -DCMAKE_C_FLAGS_RELEASE=${LIBZIP_COMPILE_FLAGS_RELEASE}
                -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=${COMPILE_DYNAMIC_MODE}
                -DBUILD_SHARED_LIBS:BOOL=${COMPILE_DYNAMIC_MODE}
                -DZLIB_LIBRARY=${ZLIB_LIBRARY}
                -DZLIB_INCLUDE_DIR=${ZLIB_INCLUDE_DIRECTORY}
                -DBZIP2_LIBRARY_DEBUG=${BZIP2_LIBRARY}
                -DBZIP2_LIBRARY_RELEASE=${BZIP2_LIBRARY}
                -DBZIP2_INCLUDE_DIR=${BZIP2_INCLUDE_DIRECTORY}
                -DLIBLZMA_LIBRARY_RELEASE=${XZ_LIBRARY}
                -DLIBLZMA_LIBRARY_DEBUG=${XZ_LIBRARY}
                -DLIBLZMA_INCLUDE_DIR=${XZ_INCLUDE_DIRECTORY}
                -Dzstd_STATIC_LIBRARY=${ZSTD_LIBRARY}
                -Dzstd_INCLUDE_DIR=${ZSTD_INCLUDE_DIRECTORY}
                -DOPENSSL_ROOT_DIR=${OPENSSL_INSTALL_DIRECTORY}
                -DOPENSSL_CRYPTO_LIBRARY=${CRYPTO_LIBRARY}
                -DOPENSSL_INCLUDE_DIR=${OPENSSL_INCLUDE_DIRECTORY}
                -DBUILD_EXAMPLES=OFF
                -DBUILD_DOC=OFF
                -DBUILD_REGRESS=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${LIBZIP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${LIBZIP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(LIBZIP_LIBRARY ${LIBZIP_LIBRARY_DIRECTORY}/${LIBZIP_LIBRARY_NAME})
    set(LIBZIP_DYNAMIC_LIBRARY ${LIBZIP_BINARY_DIRECTORY}/${LIBZIP_DYNAMIC_LIBRARY_NAME})
    set(LIBZIP_INCLUDE_DIRECTORY ${LIBZIP_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${LIBZIP_NAME})
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
include_directories(${LIBZIP_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${LIBZIP_LIBRARY})
list(APPEND DYNAMIC_LIBRARIES ${LIBZIP_DYNAMIC_LIBRARY})
