# 设置版本号、头文件名、代码库名称等。
set(PUGIXML_VERSION v1.15)
set(PUGIXML_HEADER_NAME pugixml.hpp)
set(PUGIXML_LIBRARY_NAME pugixml.lib)
set(PUGIXML_DYNAMIC_LIBRARY_NAME pugixml.dll)
set(PUGIXML_DIRECTORY ${DEPENDENCIES_DIRECTORY}/pugixml)
set(PUGIXML_INSTALL_DIRECTORY ${PUGIXML_DIRECTORY}/install)
set(PUGIXML_HEADERS_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/include)
set(PUGIXML_BINARY_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/bin)
set(PUGIXML_LIBRARY_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        PUGIXML_INCLUDE_DIRECTORY
        NAMES ${PUGIXML_HEADER_NAME}
        PATHS ${PUGIXML_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (PUGIXML_INCLUDE_DIRECTORY)
    message(STATUS "found pugixml include directory ${PUGIXML_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_file(
        PUGIXML_DYNAMIC_LIBRARY
        NAMES ${PUGIXML_DYNAMIC_LIBRARY_NAME}
        PATHS ${PUGIXML_BINARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (PUGIXML_DYNAMIC_LIBRARY)
    message(STATUS "found pugixml dynamic library ${PUGIXML_DYNAMIC_LIBRARY}")
endif ()
find_library(
        PUGIXML_LIBRARY
        NAMES ${PUGIXML_LIBRARY_NAME}
        PATHS ${PUGIXML_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (PUGIXML_LIBRARY)
    message(STATUS "found pugixml library ${PUGIXML_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT ((COMPILE_DYNAMIC_MODE AND PUGIXML_INCLUDE_DIRECTORY AND PUGIXML_LIBRARY AND PUGIXML_DYNAMIC_LIBRARY) OR (COMPILE_STATIC_MODE AND PUGIXML_INCLUDE_DIRECTORY AND PUGIXML_LIBRARY)))
    include(ExternalProject)
    set(PUGIXML_COMPILE_FLAGS "${LIBRARY_COMPILE_CXX_FLAGS} /DPUGIXML_HAS_LONG_LONG /DPUGIXML_HAS_STRING_VIEW")
    set(PUGIXML_NAME pugixml-static)
    if (COMPILE_DYNAMIC_MODE)
        set(PUGIXML_COMPILE_FLAGS "${LIBRARY_COMPILE_CXX_FLAGS} /DPUGIXML_HAS_LONG_LONG /DPUGIXML_HAS_STRING_VIEW /DPUGIXML_API=__declspec(dllexport)")
        set(PUGIXML_NAME pugixml-dynamic)
    endif ()
    set(PUGIXML_BUILD_DIRECTORY ${PUGIXML_DIRECTORY}/build)
    set(PUGIXML_SOURCE_DIRECTORY ${PUGIXML_DIRECTORY}/source)
    ExternalProject_Add(
            ${PUGIXML_NAME}
            PREFIX ${PUGIXML_DIRECTORY}
            URL https://github.com/zeux/pugixml/archive/refs/tags/${PUGIXML_VERSION}.zip
            URL_HASH SHA256=0dd4dc16e38bbc1c889d3a59660072450127bac7d19415f3cf5d5d6b25c58b35
            SOURCE_DIR ${PUGIXML_SOURCE_DIRECTORY}
            BINARY_DIR ${PUGIXML_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${PUGIXML_SOURCE_DIRECTORY} -B ${PUGIXML_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${PUGIXML_INSTALL_DIRECTORY}
                -DCMAKE_CONFIGURATION_TYPES=${CMAKE_BUILD_TYPE}
                -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
                -DCMAKE_CXX_FLAGS=${PUGIXML_COMPILE_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                # -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=${COMPILE_DYNAMIC_MODE}
                -DBUILD_SHARED_LIBS:BOOL=${COMPILE_DYNAMIC_MODE}
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(PUGIXML_INCLUDE_DIRECTORY ${PUGIXML_HEADERS_DIRECTORY})
    set(PUGIXML_LIBRARY ${PUGIXML_LIBRARY_DIRECTORY}/${PUGIXML_LIBRARY_NAME})
    set(PUGIXML_DYNAMIC_LIBRARY ${PUGIXML_BINARY_DIRECTORY}/${PUGIXML_DYNAMIC_LIBRARY_NAME})
    list(APPEND DEPENDENCIES ${PUGIXML_NAME})
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
include_directories(${PUGIXML_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${PUGIXML_LIBRARY})
list(APPEND DYNAMIC_LIBRARIES ${PUGIXML_DYNAMIC_LIBRARY})
