# 设置版本号、头文件名、代码库名称等。
set(ZSTD_NAME zstd-debug-dynamic)
set(ZSTD_HEADER_NAME zstd.h)
set(ZSTD_DYNAMIC_LIBRARY_NAME libzstd.so.1.5.7)
set(ZSTD_DIRECTORY ${DEPENDENCIES_DIRECTORY}/zstd)
set(ZSTD_INSTALL_DIRECTORY ${ZSTD_DIRECTORY}/install)
set(ZSTD_HEADERS_DIRECTORY ${ZSTD_INSTALL_DIRECTORY}/include)
set(ZSTD_LIBRARY_DIRECTORY ${ZSTD_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        ZSTD_INCLUDE_DIRECTORY
        NAMES ${ZSTD_HEADER_NAME}
        PATHS ${ZSTD_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (ZSTD_INCLUDE_DIRECTORY)
    message(STATUS "found zstd include directory ${ZSTD_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_file(
        ZSTD_DYNAMIC_LIBRARY
        NAMES ${ZSTD_DYNAMIC_LIBRARY_NAME}
        PATHS ${ZSTD_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (ZSTD_DYNAMIC_LIBRARY)
    message(STATUS "found zstd dynamic library ${ZSTD_DYNAMIC_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT (ZSTD_DYNAMIC_LIBRARY AND ZSTD_INCLUDE_DIRECTORY))
    include(ExternalProject)
    set(ZSTD_BUILD_DIRECTORY ${ZSTD_DIRECTORY}/build)
    set(ZSTD_SOURCE_DIRECTORY ${ZSTD_DIRECTORY}/source)
    ExternalProject_Add(
            ${ZSTD_NAME}
            PREFIX ${ZSTD_DIRECTORY}
            URL ${ZSTD_URL}
            URL_HASH SHA256=${ZSTD_SHA256}
            SOURCE_DIR ${ZSTD_SOURCE_DIRECTORY}
            BINARY_DIR ${ZSTD_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${ZSTD_SOURCE_DIRECTORY}/build/cmake -B ${ZSTD_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${ZSTD_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_CXX_FLAGS=${LIBRARY_COMPILE_CXX_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                -DCMAKE_C_FLAGS=${LIBRARY_COMPILE_C_FLAGS}
                -DCMAKE_C_FLAGS_DEBUG=${LIBRARY_COMPILE_C_FLAGS_DEBUG}
                -DCMAKE_C_FLAGS_RELEASE=${LIBRARY_COMPILE_C_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=ON
                -DZSTD_BUILD_TESTS=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${ZSTD_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${ZSTD_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(ZSTD_DYNAMIC_LIBRARY ${ZSTD_LIBRARY_DIRECTORY}/${ZSTD_DYNAMIC_LIBRARY_NAME})
    set(ZSTD_INCLUDE_DIRECTORY ${ZSTD_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${ZSTD_NAME})
    unset(ZSTD_BUILD_DIRECTORY)
    unset(ZSTD_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${ZSTD_INCLUDE_DIRECTORY})
list(APPEND DYNAMIC_LIBRARIES ${ZSTD_DYNAMIC_LIBRARY})

unset(ZSTD_HEADER_NAME)
unset(ZSTD_DYNAMIC_LIBRARY_NAME)
unset(ZSTD_DIRECTORY)
unset(ZSTD_INSTALL_DIRECTORY)
unset(ZSTD_HEADERS_DIRECTORY)
unset(ZSTD_LIBRARY_DIRECTORY)
