# 设置版本号、头文件名、代码库名称等。
set(BZIP2_VERSION 1ea1ac188ad4b9cb662e3f8314673c63df95a589)
set(BZIP2_HEADER_NAME bzlib.h)
set(BZIP2_LIBRARY_NAME libbz2_static.a)
if (COMPILE_DYNAMIC_MODE)
    set(BZIP2_LIBRARY_NAME bz2.a)
endif ()
set(BZIP2_DYNAMIC_LIBRARY_NAME bz2.so)
set(BZIP2_DIRECTORY ${DEPENDENCIES_DIRECTORY}/bzip2)
set(BZIP2_INSTALL_DIRECTORY ${BZIP2_DIRECTORY}/install)
set(BZIP2_HEADERS_DIRECTORY ${BZIP2_INSTALL_DIRECTORY}/include)
set(BZIP2_LIBRARY_DIRECTORY ${BZIP2_INSTALL_DIRECTORY}/lib)

# 查找头文件所在文件夹。
find_path(
        BZIP2_INCLUDE_DIRECTORY
        NAMES ${BZIP2_HEADER_NAME}
        PATHS ${BZIP2_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (BZIP2_INCLUDE_DIRECTORY)
    message(STATUS "found bzip2 include directory ${BZIP2_INCLUDE_DIRECTORY}")
endif ()

# 查找库文件。
find_file(
        BZIP2_DYNAMIC_LIBRARY
        NAMES ${BZIP2_DYNAMIC_LIBRARY_NAME}
        PATHS ${BZIP2_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (BZIP2_DYNAMIC_LIBRARY)
    message(STATUS "found bzip2 dynamic library ${BZIP2_DYNAMIC_LIBRARY}")
endif ()
find_library(
        BZIP2_LIBRARY
        NAMES ${BZIP2_LIBRARY_NAME} ${BZIP2_LIBRARY_NAME}
        PATHS ${BZIP2_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)
if (BZIP2_LIBRARY)
    message(STATUS "found bzip2 library ${BZIP2_LIBRARY}")
endif ()

# 添加外部构建项目。
if (NOT ((COMPILE_DYNAMIC_MODE AND BZIP2_DYNAMIC_LIBRARY AND BZIP2_LIBRARY AND BZIP2_INCLUDE_DIRECTORY) OR (COMPILE_STATIC_MODE AND BZIP2_LIBRARY AND BZIP2_INCLUDE_DIRECTORY)))
    include(ExternalProject)
    set(BZIP2_NAME bzip2-static)
    if (COMPILE_DYNAMIC_MODE)
        set(BZIP2_NAME bzip2-dynamic)
    endif ()
    set(BZIP2_BUILD_DIRECTORY ${BZIP2_DIRECTORY}/build)
    set(BZIP2_SOURCE_DIRECTORY ${BZIP2_DIRECTORY}/source)
    ExternalProject_Add(
            ${BZIP2_NAME}
            PREFIX ${BZIP2_DIRECTORY}
            URL https://github.com/libarchive/bzip2/archive/${BZIP2_VERSION}.zip
            SOURCE_DIR ${BZIP2_SOURCE_DIRECTORY}
            BINARY_DIR ${BZIP2_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${BZIP2_SOURCE_DIRECTORY} -B ${BZIP2_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${BZIP2_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_C_FLAGS=${LIBRARY_COMPILE_C_FLAGS}
                -DCMAKE_C_FLAGS_DEBUG=${LIBRARY_COMPILE_C_FLAGS_DEBUG}
                -DCMAKE_C_FLAGS_RELEASE=${LIBRARY_COMPILE_C_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=${COMPILE_DYNAMIC_MODE}
                -DENABLE_EXAMPLES=OFF
                -DENABLE_SHARED_LIB:BOOL=${COMPILE_DYNAMIC_MODE}
                -DENABLE_DOCS=OFF
                -DENABLE_STATIC_LIB:BOOL=${COMPILE_STATIC_MODE}
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${BZIP2_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${BZIP2_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(BZIP2_LIBRARY ${BZIP2_LIBRARY_DIRECTORY}/${BZIP2_LIBRARY_NAME})
    set(BZIP2_INCLUDE_DIRECTORY ${BZIP2_HEADERS_DIRECTORY})
    set(BZIP2_DYNAMIC_LIBRARY ${BZIP2_LIBRARY_DIRECTORY}/${BZIP2_DYNAMIC_LIBRARY_NAME})
    list(APPEND DEPENDENCIES ${BZIP2_NAME})
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
include_directories(${BZIP2_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${BZIP2_LIBRARY})
list(APPEND DYNAMIC_LIBRARIES ${BZIP2_DYNAMIC_LIBRARY})
