# 设置版本号、头文件名、依赖库名称。
set(LIBZIP_VERSION v1.11.4)
set(LIBZIP_HEADER_NAME zip.h)
set(LIBZIP_LIBRARY_NAME libzip.a)
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(LIBZIP_LIBRARY_NAME libzip.a)
endif ()

# 设置依赖安装目录。
set(LIBZIP_DIRECTORY ${DEPENDENCIES_DIRECTORY}/libzip)
file(MAKE_DIRECTORY ${LIBZIP_DIRECTORY})
set(LIBZIP_BUILD_DIRECTORY ${LIBZIP_DIRECTORY}/build)
set(LIBZIP_SOURCE_DIRECTORY ${LIBZIP_DIRECTORY}/source)
set(LIBZIP_INSTALL_DIRECTORY ${LIBZIP_DIRECTORY}/install)

# 设置依赖库路径。
find_library(
        LIBZIP_LIBRARY
        NAMES ${LIBZIP_LIBRARY_NAME}
        PATHS ${LIBZIP_INSTALL_DIRECTORY}/lib
        NO_DEFAULT_PATH
)

# 设置依赖头文件路径。
find_path(
        LIBZIP_INCLUDE_DIRECTORY
        NAMES ${LIBZIP_HEADER_NAME}
        PATHS ${LIBZIP_INSTALL_DIRECTORY}/include
        NO_DEFAULT_PATH
)

# 如果找到依赖库和头文件，则设置依赖库和头文件的路径。
if (LIBZIP_LIBRARY AND LIBZIP_INCLUDE_DIRECTORY)
    message(STATUS "found libzip library: ${LIBZIP_LIBRARY}")
    message(STATUS "found libzip include directory: ${LIBZIP_INCLUDE_DIRECTORY}")
else ()
    include(ExternalProject)
    ExternalProject_Add(
            libzip
            PREFIX ${LIBZIP_DIRECTORY}
            URL https://github.com/nih-at/libzip/archive/refs/tags/${LIBZIP_VERSION}.zip
            SOURCE_DIR ${LIBZIP_SOURCE_DIRECTORY}
            BINARY_DIR ${LIBZIP_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${LIBZIP_SOURCE_DIRECTORY} -B ${LIBZIP_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${LIBZIP_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DZLIB_LIBRARY=${ZLIB_LIBRARY}
                -DZLIB_INCLUDE_DIR=${ZLIB_INCLUDE_DIRECTORY}
                -DBZIP2_LIBRARY_DEBUG=${BZIP2_LIBRARY}
                -DBZIP2_LIBRARY_RELEASE=${BZIP2_LIBRARY}
                -DBZIP2_INCLUDE_DIR=${BZIP2_INCLUDE_DIRECTORY}
                -DLIBLZMA_LIBRARY_RELEASE=${XZ_LIBRARY}
                -DLIBLZMA_LIBRARY_DEBUG=${XZ_LIBRARY}
                -DLIBLZMA_INCLUDE_DIR=${XZ_INCLUDE_DIRECTORY}
                -Dzstd_STATIC_LIBRARY=${ZSTD_LIBRARY}
                -Dzstd_INCLUDE_DIR=${ZSTD_INCLUDE_DIRECTORY}
                -DOPENSSL_ROOT_DIR=${OPENSSL_DIRECTORY}
                -DBUILD_SHARED_LIBS=OFF
                -DCMAKE_C_FLAGS_RELEASE="-DLZMA_API_STATIC"
                -DCMAKE_C_FLAGS_DEBUG="-DLZMA_API_STATIC"
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${LIBZIP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${LIBZIP_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(LIBZIP_LIBRARY ${LIBZIP_INSTALL_DIRECTORY}/lib/${LIBZIP_LIBRARY_NAME})
    set(LIBZIP_INCLUDE_DIRECTORY ${LIBZIP_INSTALL_DIRECTORY}/include)
endif ()

include_directories(${LIBZIP_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${LIBZIP_LIBRARY})
