# 设置版本号、头文件名、代码库名称等。
set(CPP_HTTPLIB_NAME cpp-httplib-release-static)
set(CPP_HTTPLIB_HEADER_NAME httplib.h)
set(CPP_HTTPLIB_DIRECTORY ${DEPENDENCIES_DIRECTORY}/cpp-httplib)
set(CPP_HTTPLIB_INSTALL_DIRECTORY ${CPP_HTTPLIB_DIRECTORY}/install)
set(CPP_HTTPLIB_HEADERS_DIRECTORY ${CPP_HTTPLIB_INSTALL_DIRECTORY}/include)

# 查找头文件所在文件夹。
find_path(
        CPP_HTTPLIB_INCLUDE_DIRECTORY
        NAMES ${CPP_HTTPLIB_HEADER_NAME}
        PATHS ${CPP_HTTPLIB_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)
if (CPP_HTTPLIB_INCLUDE_DIRECTORY)
    message(STATUS "found cpp-httplib include directory ${CPP_HTTPLIB_INCLUDE_DIRECTORY}")
endif ()

# 添加外部构建项目。
if (NOT CPP_HTTPLIB_INCLUDE_DIRECTORY)
    include(ExternalProject)
    set(CPP_HTTPLIB_BUILD_DIRECTORY ${CPP_HTTPLIB_DIRECTORY}/build)
    set(CPP_HTTPLIB_SOURCE_DIRECTORY ${CPP_HTTPLIB_DIRECTORY}/source)
    ExternalProject_Add(
            ${CPP_HTTPLIB_NAME}
            PREFIX ${CPP_HTTPLIB_DIRECTORY}
            URL ${CPP_HTTPLIB_URL}
            URL_HASH SHA256=${CPP_HTTPLIB_SHA256}
            SOURCE_DIR ${CPP_HTTPLIB_SOURCE_DIRECTORY}
            BINARY_DIR ${CPP_HTTPLIB_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${CPP_HTTPLIB_SOURCE_DIRECTORY} -B ${CPP_HTTPLIB_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${CPP_HTTPLIB_INSTALL_DIRECTORY}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_CXX_FLAGS=${LIBRARY_COMPILE_CXX_FLAGS}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_COMPILE_CXX_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_COMPILE_CXX_FLAGS_RELEASE}
                -DBUILD_SHARED_LIBS:BOOL=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${CPP_HTTPLIB_BUILD_DIRECTORY} --parallel --config ${CMAKE_BUILD_TYPE} --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${CPP_HTTPLIB_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(CPP_HTTPLIB_INCLUDE_DIRECTORY ${CPP_HTTPLIB_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${CPP_HTTPLIB_NAME})
    unset(CPP_HTTPLIB_BUILD_DIRECTORY)
    unset(CPP_HTTPLIB_SOURCE_DIRECTORY)
endif ()

# 导入头文件文件夹、链接代码库、复制动态代码库。
list(APPEND INCLUDES ${CPP_HTTPLIB_INCLUDE_DIRECTORY})

unset(CPP_HTTPLIB_HEADER_NAME)
unset(CPP_HTTPLIB_DIRECTORY)
unset(CPP_HTTPLIB_INSTALL_DIRECTORY)
unset(CPP_HTTPLIB_HEADERS_DIRECTORY)
