# 设置依赖库的编译参数。
set(LIBRARY_COMPILE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
set(LIBRARY_COMPILE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_GLIBCXX_DEBUG")
set(LIBRARY_COMPILE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
set(LIBRARY_COMPILE_C_FLAGS "${CMAKE_C_FLAGS}")
set(LIBRARY_COMPILE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -D_GLIBCXX_DEBUG")
set(LIBRARY_COMPILE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
if (COMPILE_DYNAMIC_MODE)
    set(LIBRARY_COMPILE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    set(LIBRARY_COMPILE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_GLIBCXX_DEBUG")
    set(LIBRARY_COMPILE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
    set(LIBRARY_COMPILE_C_FLAGS "${CMAKE_C_FLAGS}")
    set(LIBRARY_COMPILE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -D_GLIBCXX_DEBUG")
    set(LIBRARY_COMPILE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
endif ()

# 设置编译参数。
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -finput-charset=UTF-8 -fexec-charset=UTF-8")
set(TMP_CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} --all-warnings -pedantic -Winline -O0 -Wall -g3 -D_GLIBCXX_DEBUG -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function")
set(TMP_CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -g0")
if (COMPILE_DYNAMIC_MODE)
    set(TMP_CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} --all-warnings -pedantic -Winline -O0 -Wall -g3 -D_GLIBCXX_DEBUG -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function")
    set(TMP_CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -g0")
endif ()
set(CMAKE_CXX_FLAGS_DEBUG "${TMP_CMAKE_CXX_FLAGS_DEBUG}")
set(CMAKE_CXX_FLAGS_RELEASE "${TMP_CMAKE_CXX_FLAGS_RELEASE}")
unset(TMP_CMAKE_CXX_FLAGS_DEBUG)
unset(TMP_CMAKE_CXX_FLAGS_RELEASE)

# 添加依赖。
include(cmakes/linux/libzip.cmake)
include(cmakes/linux/jwt-cpp.cmake)
include(cmakes/linux/openssl.cmake)
include(cmakes/linux/zlib.cmake)
include(cmakes/linux/zstd.cmake)
include(cmakes/linux/argparse.cmake)
include(cmakes/linux/bzip2.cmake)
include(cmakes/linux/cpp-httplib.cmake)
include(cmakes/linux/pugixml.cmake)
include(cmakes/linux/xz.cmake)
include(cmakes/linux/yaml-cpp.cmake)

list(APPEND DEFINITIONS "-DLINUX")
